networks:
  traefik:
    external: true
  app-network:
    driver: bridge

services:
  database:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1
    volumes:
      - ./docker/database:/var/lib/mysql
    networks:
      - app-network

  backend:
    build:
      args:
        HOST_USER: user
        HOST_UID: 1000
      context: .
      dockerfile: ./docker/backend.dockerfile
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network

  backend-web:
    image: nginx:latest
    depends_on:
      - backend
      - database
    restart: unless-stopped
    working_dir: /var/www/html
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.ald-backend.rule=${BACKEND_HOST}
      - traefik.http.routers.ald-backend.entrypoints=https
      - traefik.http.routers.ald-backend.tls=true
      - traefik.http.routers.ald-backend.service=ald-backend@docker
      - traefik.log.level=${LOG_LEVEL}
      - traefik.http.services.ald-backend.loadbalancer.server.port=80
    volumes:
      - ./backend:/var/www/html
      - ./docker/backend.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
      - traefik

  frontend:
    image: nginx:latest
    depends_on:
      - backend-web
    restart: unless-stopped
    working_dir: /var/www/html
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.ald-frontend.rule=${FRONTEND_HOST}
      - traefik.http.routers.ald-frontend.entrypoints=https
      - traefik.http.routers.ald-frontend.tls=true
      - traefik.log.level=${LOG_LEVEL}
      - traefik.http.services.ald-frontend.loadbalancer.server.port=80
    volumes:
      - ./frontend/dist/html:/var/www/html
      - ./docker/frontend.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
      - traefik
